### ISSUE TITLE
Crash while attempting to play Pac-Man

### ISSUE THREAD

**Issue by Techokami** [KenLPham/ArcadeMod#2]
Relevent version numbers:
Minecraft 1.12.2
Forge 14.23.3.2655
Arcade Mod 2.1.1

[Crash Log pastebin link](https://pastebin.com/57zXfHLr)

I wanted to give this mod a spin, and in particular I wanted to see how good your Pac-Man implementation is. So I crafted a Pac-Man cabinet and placed it in the world. It needed coins, so I made the 4 needed coins... it refused to take the coins and play the game. So I changed the configuration to free play mode and tried again... and my client crashed.

Also, some feedback on the mod from the brief period I was using it for:
- The arcade cabinets are simultaneously too detailed and not detailed enough. The models are very fancy, yes, but there's no real detailing on them (like control panels, side art, marquee art) and they look out of place in the world of Minecraft. Maybe instead, you could have blockier models with pixel artwork on them?
- Crafting the arcade cabinets feels too... easy? It's just wood, wool, a glass pane, and one bit of redstone. Personally I would have gone with a micro-crafting setup like other tech mods, using some harder-to-get materials like glowstone for making the monitor, with some alternate recipe sets to integrate with other tech mods like OpenComputers (e.g. you need a Tier 2 screen instead of a dedicated monitor recipe). That way it would feel like an accomplishment to make a big, game-filled arcade.
- Rather than hard code all the games in Java, why not instead use a Java-based NES emulator on the client side and run NES games? You can get around legalities by publishing the mod with freely-distributable homebrew games, and provide support for adding more games via resource packs. Then players can find game PCBs in the world (either from trading with villagers, or as mystery PCBs in dungeon loot chests that you identify by using) and install them into cabinets to turn them into an arcade cabinet for said game. You could even go the extra mile and integrate with OpenComputers to add the ability for users to burn ROMs onto custom arcade PCBs. Though, this would interfere with the concepts of using coins and getting tickets...

**Comment by KenLPham** [comment]
To comment on the feedback:

1. I know what you mean, I plan on redesigning the models later. For the textures, I'm not a texture artists so the textures that I did make (didn't have the time to bind them to the model yet, but their in the resource folder) look horrible. If you look at the original models, you can see what I mean with the textures.

2. I decided to make the crafting easy because you're just making a block to play a game. It doesn't have much value like other mods were there are 50 different recipes to create one block. I can, however, possibly make a hard and easy crafting option that can be turned on and off in the config, if anyone wants.

3. I decided to hard code all the games because it gives me a chance to learn Java. I'm still new and thought learning how to make these games would help refine my skills. I might have to go with a NES emulator soon because I might not have enough time to work on this mod in the coming months.

**Comment by Techokami** [comment]
For texturing arcade cabinets, you could look into a creative opt-out and see about rendering banners on them. So you still have plain arcade cabinets, but use a banner on them to change the marquee/kickplate colors to match the base color of the banner, then put the banner design on the sides. This would work well with a NES emulation setup, with limiting each cabinet to one game: you have a generic cabinet that can play any game, and then the player can choose the game and the cabinet artwork themselves to make for a more unique machine for their base. Though I do have to commend you on your effort to recreate the Midway Pac-Man cabinet art at such small sizes! It honestly doesn't look as bad as you think.

For the actual arcade cabinet models, a voxel model would look more in-line with the Minecraft art style, imho. Check out these that I made with Chisels & Bits for my base in a modded Minecraft server: 
![2018-04-29_14 20 56](https://user-images.githubusercontent.com/1530728/39873828-fd13d9ac-5439-11e8-9cfb-d4ff3998a577.png)
These do take up more width and depth than a single block, but it does convey the idea I have for the aesthetics of an arcade machine in Minecraft.

Also, I should mention that a lot of the ideas I've mentioned in here are, more or less, from the ideas I had for an arcade-in-Minecraft mod, after seeing an old modjam project by NullPointerException go nowhere and get a messed up design doc.

**Comment by KenLPham** [comment]
Update 2.1.2 should fix the crashing caused by disabling the use of coins.

Coins not working might still be a problem (Through my testing, Pong was the only game affected) Which is interesting as all the games us the same code for the button.

As for the models. I want to have the bezels actually one pixel thick rather than them being 1/8 of a pixel thin to make it more Minecraft-like, but I would also like to have some angles as it would look much nicer and easier to model.

The problem with a generic cabinet is that I would like to make the cabinets look like the real ones. (unless the game doesn't have one, then it uses a generic cabinet)
